# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  BuildConfiguration: 'Release'


steps:
  - task: DotNetCoreCLI@2
    displayName: Restore (only name)
    inputs:
      command: restore
  
  - task: DotNetCoreCLI@2
    displayName: Build (only name)
    inputs:
      arguments: '--configuration $(BuildConfiguration)'   #build into Relase env

  - task: DotNetCoreCLI@2
    displayName: Publish (only name)
    inputs:
      command: publish
      publishWebProjects: true
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'  ##output as default dir to publish artifact into relase env
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact (name only)'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)' #defaul location
